name: Publish dataset zips

on:
  push:
    branches: [ "main" ]
    paths:
      - "datasets/audio/**/*"
      - "datasets/image/**/*"
      - ".github/workflows/publish-datasets.yml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.PUSH_TOKEN }}

    - name: Zip Files
      run: |
        ln -s datasets data
        tar -czf att-faces.tar.gz data/image/att-faces
        tar -czf metfaces.tar.gz data/image/metfaces
        tar -czf clouds.tar.gz data/image/clouds
        tar -czf flowers.tar.gz data/image/flowers
        tar -czf bob-ross.tar.gz data/image/bob-ross
        tar --exclude='data/audio/instruments/raw' -czf instruments.tar.gz data/audio/instruments
        tar --exclude='data/image/0801-500/all' -czf 0801-500.tar.gz data/image/0801-500
        tar --exclude='data/image/forest-tree/raw' -czf forest-tree.tar.gz data/image/forest-tree
        tar --exclude='data/image/lfw/raw' -czf lfw.tar.gz data/image/lfw

    - name: Tag Release
      id: tag
      run: |
        GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c 1-8)
        git config --local user.name "github-actions[bot]"
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        TAG_NAME=${{ github.ref_name }}-$(git log --format=%h -1)
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_OUTPUT
        git tag $TAG_NAME
        git push origin $TAG_NAME

    - name: Release
      uses: softprops/action-gh-release@v2
      with:
        files: |
          *.tar.gz
        tag_name: ${{ steps.tag.outputs.TAG_NAME }}
        token: ${{ secrets.PUSH_TOKEN }}
